### ISSUE TITLE
为每一篇文章底部添加Contributors

### ISSUE THREAD

**Issue by zlxiao97** [digitalchina-frontend/digitalchina-frontend.github.io#3]
效果参考[vueuse 网站](https://vueuse.org/core/useFileSystemAccess/#contributors)

**Comment by zlxiao97** [comment]
大致实现思路为：

- 构建阶段：获取所有文章的 `.md` 文件路径并写入 JSON 文件
- 运行阶段：读取 JSON 文件中的文件路径并执行 `git log` (通过 simple-git)，处理获取到的数据并传入Contributors插件

有两个问题需要调研：
1. 是否需要在构建阶段生成 JSON 文件
2. 是否可以将 `git log` 中获取的数据映射到 gitHub 头像

有以下第三方库的基础用法需要调研：
1. simple-git
2. fast-glob
3. gray-matter

**Comment by Cat-Ring** [comment]
![企业微信截图_16520892739850](https://user-images.githubusercontent.com/33746164/167383961-0470bec1-324d-4024-bd3c-c69e5e5577dc.png)

**Comment by Cat-Ring** [comment]
关于github头像
![github头像托管于gravatar](https://user-images.githubusercontent.com/33746164/167384331-afad7396-4e36-4e99-bfe5-e520134657c9.png)

**Comment by Cat-Ring** [comment]
关于gray-matter：
[vuepress中为何使用gray-matter](https://vuepress.vuejs.org/zh/guide/frontmatter.html#%E5%85%B6%E4%BB%96%E6%A0%BC%E5%BC%8F%E7%9A%84-front-matter)
gray-matter，从字符串和文件中解析front-matter，默认解析YAML front-matter，但也支持 YAML、JSON、TOML 或 Coffee Front-Matter，并提供设置自定义分隔符的选项。

**Comment by zlxiao97** [comment]
> 大致实现思路为：
> 
> * 构建阶段：获取所有文章的 `.md` 文件路径并写入 JSON 文件
> * 运行阶段：读取 JSON 文件中的文件路径并执行 `git log` (通过 simple-git)，处理获取到的数据并传入Contributors插件
> 
> 有两个问题需要调研：
> 
> 1. 是否需要在构建阶段生成 JSON 文件
> 2. 是否可以将 `git log` 中获取的数据映射到 gitHub 头像
> 
> 有以下第三方库的基础用法需要调研：
> 
> 1. simple-git
> 2. fast-glob
> 3. gray-matter

更新一下思路：
+ 编译阶段：利用 [extendPageData API]() 获取文章文件路径并执行 `git log`（可能可以被 GitHub Search API 中的 /search/commit 替代）
+ 运行阶段：在 `Layout` 组件中插入 `Contributor` 组件，通过 `this.$page` 获取数据即可
